import { Product } from '@/types/product.types';
import { Supplier } from '@/types/supplier.types';
import { PurchaseOrder } from '@/types/purchase.types';
import { SalesOrder, Customer } from '@/types/order.types';
import { InventoryLevel, Allocation, Dispatch } from '@/types/inventory.types';
import { Warehouse, Zone, Bin, Worker, UserProfile } from '@/types/database.types';
import { ARIADecision, ARIASummary } from '@/types/aria.types';
import { PickingTask, PackingTask, QCCheck } from '@/types/lifecycle.types';

export const INITIAL_USER_PROFILES: UserProfile[] = [
  {
    id: 'user-001',
    full_name: 'Alexander Sterling',
    email: 'admin@ariawms.io',
    role: 'admin',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-002',
    full_name: 'Elena Rostova',
    email: 'manager@ariawms.io',
    role: 'inventory_manager',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-003',
    full_name: 'Marcus Vance',
    email: 'staff@ariawms.io',
    role: 'staff',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-004',
    full_name: 'Sarah Chen',
    email: 'supervisor@ariawms.io',
    role: 'supervisor',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'supp-101',
    company_name: 'TechMart Microelectronics India',
    contact_person: 'Rajesh Kumar',
    email: 'procurement@techmart.in',
    phone: '+91 98765 43210',
    address: { street: 'Electronics City Phase 1', city: 'Bengaluru', state: 'Karnataka', country: 'India', zip: '560100' },
    payment_terms: 'Net 30',
    rating: 4.85,
    is_active: true,
    created_at: '2025-01-15T00:00:00Z',
    updated_at: '2026-02-10T00:00:00Z',
  },
  {
    id: 'supp-102',
    company_name: 'Apex Components Corp',
    contact_person: 'David Miller',
    email: 'orders@apexcomp.com',
    phone: '+1 408 555 0199',
    address: { street: '450 Innovation Way', city: 'San Jose', state: 'CA', country: 'USA', zip: '95134' },
    payment_terms: 'Net 15',
    rating: 4.92,
    is_active: true,
    created_at: '2025-02-01T00:00:00Z',
    updated_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'supp-103',
    company_name: 'ColdChain Logistics & Storage GmbH',
    contact_person: 'Hans Gruber',
    email: 'vertrieb@coldchain.de',
    phone: '+49 89 1234 5678',
    address: { street: 'Logistikpark 12', city: 'Munich', country: 'Germany', zip: '80331' },
    payment_terms: 'Net 45',
    rating: 4.60,
    is_active: true,
    created_at: '2025-03-10T00:00:00Z',
    updated_at: '2026-04-12T00:00:00Z',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    sku: 'SKU-LAPT-001',
    barcode: '8901234567890',
    name: 'ProBook Enterprise Laptop 15" i7 32GB',
    description: 'Industrial ultra-rugged laptop for enterprise logistics and fleet tracking.',
    category: 'Electronics',
    sub_category: 'Laptops',
    brand: 'ProBook Tech',
    purchase_price: 850.0,
    selling_price: 1299.99,
    weight_kg: 1.85,
    dimensions_cm: { l: 36, w: 25, h: 2 },
    reorder_threshold: 10,
    reorder_quantity: 50,
    supplier_id: 'supp-101',
    supplier_name: 'TechMart Microelectronics India',
    requires_cold_storage: false,
    is_fragile: true,
    is_active: true,
    created_at: '2025-01-20T00:00:00Z',
    updated_at: '2026-08-15T00:00:00Z',
  },
  {
    id: 'prod-002',
    sku: 'SKU-MONI-4K27',
    barcode: '8901234567891',
    name: 'UltraClear 27" 4K IPS HDR Monitor',
    description: 'Color-calibrated 4K display with USB-C 90W PD charging.',
    category: 'Electronics',
    sub_category: 'Displays',
    brand: 'UltraClear',
    purchase_price: 320.0,
    selling_price: 499.0,
    weight_kg: 5.4,
    dimensions_cm: { l: 62, w: 42, h: 12 },
    reorder_threshold: 15,
    reorder_quantity: 40,
    supplier_id: 'supp-102',
    supplier_name: 'Apex Components Corp',
    requires_cold_storage: false,
    is_fragile: true,
    is_active: true,
    created_at: '2025-02-10T00:00:00Z',
    updated_at: '2026-08-10T00:00:00Z',
  },
  {
    id: 'prod-003',
    sku: 'SKU-SENS-COLD',
    barcode: '8901234567892',
    name: 'IoT Thermal Cold-Chain Sensor Node',
    description: 'Real-time wireless temperature & humidity monitor (-40°C to +85°C).',
    category: 'Sensors',
    sub_category: 'IoT Hardware',
    brand: 'SensNet',
    purchase_price: 45.0,
    selling_price: 89.5,
    weight_kg: 0.12,
    dimensions_cm: { l: 8, w: 5, h: 2 },
    reorder_threshold: 25,
    reorder_quantity: 100,
    supplier_id: 'supp-103',
    supplier_name: 'ColdChain Logistics & Storage GmbH',
    requires_cold_storage: true,
    is_fragile: false,
    is_active: true,
    created_at: '2025-03-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'prod-004',
    sku: 'SKU-BATT-LIPO',
    barcode: '8901234567893',
    name: 'High-Capacity Lithium Polymer Cell 20,000mAh',
    description: 'Industrial lithium cell with integrated safety PCM board.',
    category: 'Power Systems',
    sub_category: 'Batteries',
    brand: 'VoltPro',
    purchase_price: 28.5,
    selling_price: 55.0,
    weight_kg: 0.38,
    dimensions_cm: { l: 14, w: 7, h: 2 },
    reorder_threshold: 30,
    reorder_quantity: 150,
    supplier_id: 'supp-101',
    supplier_name: 'TechMart Microelectronics India',
    requires_cold_storage: false,
    is_fragile: false,
    is_active: true,
    created_at: '2025-03-15T00:00:00Z',
    updated_at: '2026-08-16T00:00:00Z',
  },
  {
    id: 'prod-005',
    sku: 'SKU-CABL-CAT7',
    barcode: '8901234567894',
    name: 'Shielded Cat7 Industrial Ethernet Cable 50m',
    description: 'Heavy-duty double shielded S/FTP 10Gbps high-speed network cable.',
    category: 'Networking',
    sub_category: 'Cables',
    brand: 'WireMaster',
    purchase_price: 18.0,
    selling_price: 34.99,
    weight_kg: 1.2,
    dimensions_cm: { l: 25, w: 25, h: 6 },
    reorder_threshold: 40,
    reorder_quantity: 200,
    supplier_id: 'supp-102',
    supplier_name: 'Apex Components Corp',
    requires_cold_storage: false,
    is_fragile: false,
    is_active: true,
    created_at: '2025-04-01T00:00:00Z',
    updated_at: '2026-08-12T00:00:00Z',
  },
];

export const INITIAL_WAREHOUSES: Warehouse[] = [
  {
    id: 'wh-001',
    name: 'Central Megahub Alpha',
    city: 'Chicago, IL',
    address: '100 Logistics Parkway, Chicago, IL 60666',
    total_zones: 5,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'wh-002',
    name: 'Pacific Northwest Hub',
    city: 'Seattle, WA',
    address: '450 Harbor Way, Seattle, WA 98101',
    total_zones: 4,
    is_active: true,
    created_at: '2025-03-01T00:00:00Z',
  },
];

export const INITIAL_ZONES: Zone[] = [
  { id: 'zone-01', warehouse_id: 'wh-001', name: 'Zone A - High Velocity Storage', zone_type: 'picking', capacity_units: 1000, created_at: '2025-01-01T00:00:00Z' },
  { id: 'zone-02', warehouse_id: 'wh-001', name: 'Zone B - Bulk Pallet Storage', zone_type: 'storage', capacity_units: 2500, created_at: '2025-01-01T00:00:00Z' },
  { id: 'zone-03', warehouse_id: 'wh-001', name: 'Zone C - Cold Chain Vault', zone_type: 'storage', capacity_units: 500, created_at: '2025-01-01T00:00:00Z' },
  { id: 'zone-04', warehouse_id: 'wh-001', name: 'Zone D - Outbound Packing & QC', zone_type: 'packing', capacity_units: 400, created_at: '2025-01-01T00:00:00Z' },
];

export const INITIAL_BINS: Bin[] = [
  { id: 'bin-A123', zone_id: 'zone-01', bin_code: 'A-12-3', aisle: 'A', shelf: 12, position: 3, is_occupied: true, created_at: '2025-01-01T00:00:00Z' },
  { id: 'bin-A124', zone_id: 'zone-01', bin_code: 'A-12-4', aisle: 'A', shelf: 12, position: 4, is_occupied: true, created_at: '2025-01-01T00:00:00Z' },
  { id: 'bin-B011', zone_id: 'zone-02', bin_code: 'B-01-1', aisle: 'B', shelf: 1, position: 1, is_occupied: true, created_at: '2025-01-01T00:00:00Z' },
  { id: 'bin-C052', zone_id: 'zone-03', bin_code: 'C-05-2', aisle: 'C', shelf: 5, position: 2, is_occupied: true, created_at: '2025-01-01T00:00:00Z' },
  { id: 'bin-D021', zone_id: 'zone-04', bin_code: 'D-02-1', aisle: 'D', shelf: 2, position: 1, is_occupied: false, created_at: '2025-01-01T00:00:00Z' },
];

export const INITIAL_INVENTORY: InventoryLevel[] = [
  {
    id: 'inv-001',
    product_id: 'prod-001',
    bin_id: 'bin-A123',
    quantity_available: 8,
    quantity_reserved: 2,
    quantity_damaged: 0,
    batch_number: 'BATCH-20260801-A',
    expiry_date: '2027-08-01',
    received_at: '2026-08-01T10:00:00Z',
    last_movement_at: '2026-08-17T14:30:00Z',
    sku: 'SKU-LAPT-001',
    product_name: 'ProBook Enterprise Laptop 15" i7 32GB',
    bin_code: 'A-12-3',
  },
  {
    id: 'inv-002',
    product_id: 'prod-002',
    bin_id: 'bin-A124',
    quantity_available: 24,
    quantity_reserved: 6,
    quantity_damaged: 1,
    batch_number: 'BATCH-20260715-B',
    expiry_date: '2028-01-01',
    received_at: '2026-07-15T09:00:00Z',
    last_movement_at: '2026-08-16T11:20:00Z',
    sku: 'SKU-MONI-4K27',
    product_name: 'UltraClear 27" 4K IPS HDR Monitor',
    bin_code: 'A-12-4',
  },
  {
    id: 'inv-003',
    product_id: 'prod-003',
    bin_id: 'bin-C052',
    quantity_available: 65,
    quantity_reserved: 10,
    quantity_damaged: 0,
    batch_number: 'BATCH-20260810-C',
    expiry_date: '2026-12-31',
    received_at: '2026-08-10T08:00:00Z',
    last_movement_at: '2026-08-17T16:00:00Z',
    sku: 'SKU-SENS-COLD',
    product_name: 'IoT Thermal Cold-Chain Sensor Node',
    bin_code: 'C-05-2',
  },
  {
    id: 'inv-004',
    product_id: 'prod-004',
    bin_id: 'bin-B011',
    quantity_available: 110,
    quantity_reserved: 15,
    quantity_damaged: 2,
    batch_number: 'BATCH-20260601-D',
    expiry_date: '2027-06-01',
    received_at: '2026-06-01T12:00:00Z',
    last_movement_at: '2026-08-14T09:15:00Z',
    sku: 'SKU-BATT-LIPO',
    product_name: 'High-Capacity Lithium Polymer Cell 20,000mAh',
    bin_code: 'B-01-1',
  },
  {
    id: 'inv-005',
    product_id: 'prod-005',
    bin_id: 'bin-A123',
    quantity_available: 180,
    quantity_reserved: 20,
    quantity_damaged: 0,
    batch_number: 'BATCH-20260520-E',
    expiry_date: '2029-05-20',
    received_at: '2026-05-20T11:00:00Z',
    last_movement_at: '2026-08-15T15:00:00Z',
    sku: 'SKU-CABL-CAT7',
    product_name: 'Shielded Cat7 Industrial Ethernet Cable 50m',
    bin_code: 'A-12-3',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-901',
    name: 'Vanguard Aerospace LLC',
    email: 'procurement@vanguardaerospace.com',
    phone: '+1 206 555 9811',
    company: 'Vanguard Aerospace',
    address: { street: '1000 Airport Way', city: 'Seattle', state: 'WA', zip: '98108' },
    tier: 'vip',
    total_orders: 42,
    total_spend: 185400.0,
    created_at: '2025-01-10T00:00:00Z',
  },
  {
    id: 'cust-902',
    name: 'Quantum BioTech Labs',
    email: 'supplies@quantumbio.com',
    phone: '+1 617 555 3300',
    company: 'Quantum BioTech',
    address: { street: '75 Sidney St', city: 'Cambridge', state: 'MA', zip: '02139' },
    tier: 'priority',
    total_orders: 18,
    total_spend: 64200.0,
    created_at: '2025-02-15T00:00:00Z',
  },
  {
    id: 'cust-903',
    name: 'Nexus Retail Distribution',
    email: 'orders@nexusretail.com',
    phone: '+1 312 555 7711',
    company: 'Nexus Retail',
    address: { street: '500 N Michigan Ave', city: 'Chicago', state: 'IL', zip: '60611' },
    tier: 'standard',
    total_orders: 9,
    total_spend: 19800.0,
    created_at: '2025-04-01T00:00:00Z',
  },
];

export const INITIAL_ORDERS: SalesOrder[] = [
  {
    id: 'ord-8001',
    order_number: 'ORD-20260818-8001',
    customer_id: 'cust-901',
    customer_name: 'Vanguard Aerospace LLC',
    customer_email: 'procurement@vanguardaerospace.com',
    customer_tier: 'vip',
    warehouse_id: 'wh-001',
    status: 'allocated',
    payment_status: 'paid',
    priority_score: 92.5,
    priority_level: 'critical',
    requested_delivery_date: '2026-08-19',
    sla_deadline: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(), // 4 hrs from now
    total_value: 7799.94,
    total_cost: 5100.0,
    total_weight_kg: 12.6,
    item_count: 3,
    created_at: '2026-08-18T06:00:00Z',
    updated_at: '2026-08-18T07:15:00Z',
    items: [
      {
        id: 'oi-101',
        order_id: 'ord-8001',
        product_id: 'prod-001',
        quantity_ordered: 2,
        quantity_allocated: 2,
        quantity_picked: 0,
        quantity_packed: 0,
        unit_price: 1299.99,
        unit_cost: 850.0,
        sku: 'SKU-LAPT-001',
        barcode: '8901234567890',
        product_name: 'ProBook Enterprise Laptop 15" i7 32GB',
        bin_code: 'A-12-3',
      },
      {
        id: 'oi-102',
        order_id: 'ord-8001',
        product_id: 'prod-002',
        quantity_ordered: 1,
        quantity_allocated: 1,
        quantity_picked: 0,
        quantity_packed: 0,
        unit_price: 499.0,
        unit_cost: 320.0,
        sku: 'SKU-MONI-4K27',
        barcode: '8901234567891',
        product_name: 'UltraClear 27" 4K IPS HDR Monitor',
        bin_code: 'A-12-4',
      },
    ],
  },
  {
    id: 'ord-8002',
    order_number: 'ORD-20260818-8002',
    customer_id: 'cust-902',
    customer_name: 'Quantum BioTech Labs',
    customer_email: 'supplies@quantumbio.com',
    customer_tier: 'priority',
    warehouse_id: 'wh-001',
    status: 'picking',
    payment_status: 'paid',
    priority_score: 74.0,
    priority_level: 'high',
    requested_delivery_date: '2026-08-20',
    sla_deadline: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
    total_value: 2237.5,
    total_cost: 1125.0,
    total_weight_kg: 3.0,
    item_count: 25,
    created_at: '2026-08-18T05:30:00Z',
    updated_at: '2026-08-18T07:45:00Z',
    items: [
      {
        id: 'oi-201',
        order_id: 'ord-8002',
        product_id: 'prod-003',
        quantity_ordered: 25,
        quantity_allocated: 25,
        quantity_picked: 10,
        quantity_packed: 0,
        unit_price: 89.5,
        unit_cost: 45.0,
        sku: 'SKU-SENS-COLD',
        barcode: '8901234567892',
        product_name: 'IoT Thermal Cold-Chain Sensor Node',
        bin_code: 'C-05-2',
      },
    ],
  },
  {
    id: 'ord-8003',
    order_number: 'ORD-20260818-8003',
    customer_id: 'cust-903',
    customer_name: 'Nexus Retail Distribution',
    customer_email: 'orders@nexusretail.com',
    customer_tier: 'standard',
    warehouse_id: 'wh-001',
    status: 'created',
    payment_status: 'pending',
    priority_score: 45.0,
    priority_level: 'medium',
    requested_delivery_date: '2026-08-22',
    sla_deadline: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    total_value: 1749.5,
    total_cost: 900.0,
    total_weight_kg: 6.0,
    item_count: 50,
    created_at: '2026-08-18T07:50:00Z',
    updated_at: '2026-08-18T07:50:00Z',
    items: [
      {
        id: 'oi-301',
        order_id: 'ord-8003',
        product_id: 'prod-005',
        quantity_ordered: 50,
        quantity_allocated: 0,
        quantity_picked: 0,
        quantity_packed: 0,
        unit_price: 34.99,
        unit_cost: 18.0,
        sku: 'SKU-CABL-CAT7',
        barcode: '8901234567894',
        product_name: 'Shielded Cat7 Industrial Ethernet Cable 50m',
        bin_code: 'A-12-3',
      },
    ],
  },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'po-501',
    po_number: 'PO-20260818-9182',
    supplier_id: 'supp-101',
    supplier_name: 'TechMart Microelectronics India',
    warehouse_id: 'wh-001',
    warehouse_name: 'Central Megahub Alpha',
    status: 'ordered',
    total_amount: 42500.0,
    expected_delivery: '2026-08-21',
    notes: 'Urgent restock of ProBook laptops for Q3 enterprise fleet rollout.',
    created_at: '2026-08-17T10:00:00Z',
    updated_at: '2026-08-17T11:00:00Z',
    items: [
      {
        id: 'poi-01',
        purchase_order_id: 'po-501',
        product_id: 'prod-001',
        quantity_ordered: 50,
        quantity_received: 0,
        unit_cost: 850.0,
        total_cost: 42500.0,
        sku: 'SKU-LAPT-001',
        product_name: 'ProBook Enterprise Laptop 15" i7 32GB',
      },
    ],
  },
];

export const INITIAL_WORKERS: Worker[] = [
  {
    id: 'wrk-01',
    full_name: 'Dmitri Volkov',
    role: 'Lead Wave Picker',
    shift: 'Morning',
    assigned_zone: 'Zone A',
    pick_speed_items_per_hr: 142,
    accuracy_rate: 99.4,
    status: 'active',
    tasks_completed_today: 18,
  },
  {
    id: 'wrk-02',
    full_name: 'Sarah Jenkins',
    role: 'QC Inspector',
    shift: 'Morning',
    assigned_zone: 'Zone D',
    pick_speed_items_per_hr: 110,
    accuracy_rate: 99.8,
    status: 'active',
    tasks_completed_today: 24,
  },
  {
    id: 'wrk-03',
    full_name: 'Carlos Mendez',
    role: 'Forklift & Putaway Operator',
    shift: 'Evening',
    assigned_zone: 'Zone B',
    pick_speed_items_per_hr: 95,
    accuracy_rate: 98.9,
    status: 'active',
    tasks_completed_today: 12,
  },
];

export const INITIAL_ARIA_DECISIONS: ARIADecision[] = [
  {
    id: 'dec-101',
    decision_type: 'stockout_reorder',
    severity: 'critical',
    affected_product_id: 'prod-001',
    detected_problem: {
      title: 'Low Stock Anomaly: SKU-LAPT-001',
      description: 'Stock available is 8 units (Reorder threshold: 10 units). VIP order velocity spike detected.',
    },
    root_cause_analysis: 'Unscheduled bulk order from VIP client Vanguard Aerospace consumed 40% of safety buffer within 3 hours.',
    confidence_score: 94.5,
    suggested_action: {
      title: 'Issue Restock PO to TechMart',
      action_type: 'create_po',
      endpoint: '/api/purchases',
      method: 'POST',
      body: { supplier_id: 'supp-101', warehouse_id: 'wh-001', items: [{ product_id: 'prod-001', quantity: 50, unit_cost: 850 }] },
    },
    execution_mode: 'recommendation',
    execution_status: 'pending',
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'dec-102',
    decision_type: 'priority_override',
    severity: 'warning',
    affected_order_id: 'ord-8001',
    detected_problem: {
      title: 'SLA Escalation Alert',
      description: 'Order ORD-20260818-8001 has 4 hours remaining until SLA deadline breach.',
    },
    root_cause_analysis: 'High order volume in Zone A picking queue caused standard FIFO picking to lag.',
    confidence_score: 89.0,
    suggested_action: {
      title: 'Escalate Order Priority to Critical',
      action_type: 'advance_stage',
      endpoint: '/api/orders/ord-8001/advance',
      method: 'POST',
      body: { target_stage: 'picking' },
    },
    execution_mode: 'recommendation',
    execution_status: 'pending',
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_ARIA_SUMMARIES: ARIASummary[] = [
  {
    id: 'sum-01',
    summary_type: 'shift_debrief',
    period_start: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    period_end: new Date().toISOString(),
    health_score: 92,
    key_highlights: [
      '184 Sales Orders processed with 99.1% SLA compliance rate.',
      'PO-20260818-9182 submitted to TechMart India for 50 ProBook laptops.',
      'Average wave picking travel time reduced by 14% via serpentine routing.',
    ],
    critical_blockers: [
      'SKU-LAPT-001 safety stock reached 8 units; restock order active.',
      'Bin A-12-3 requires physical cycle count due to barcode scan retry.',
    ],
    actions_taken_count: 6,
    recommended_priorities: [
      'Execute cycle count on Zone A picking bins.',
      'Expedite receiving staging for incoming TechMart shipment.',
    ],
    raw_ai_narrative: 'Shift operations maintained high velocity despite elevated VIP order volume. All critical SLA windows were protected.',
    created_at: new Date().toISOString(),
  },
];
